### ISSUE TITLE
Re: Bechmarking (fast) dplyr alternatives

### ISSUE THREAD

**Issue by SebKrantz** [shokru/coqueret.github.io#1]
Hi, I came across your post [here](http://www.gcoqueret.com/files/misc/benchmark_dplyr.html) by coincidence. Just one remark: to benchmark *collapse*, you at least need to use it's own functions for grouping and data manupilation e.g. `fgroup_by()`, `fsummarsie()`, `fselect()` and `fmutate()` instead of the dplyr versions. Most of the performance differences are realized at the grouping stage, not at the stage of final computation. 

Another thing to be aware of is different library defaults. For example *arrow* performs unsorted grouping i.e. the groups are not sorted upon aggregation. *collapse*, in line with *dplyr* does sorted grouping, which has an additional cost. So for the comparison with arrow, using `fgroup_by(..., sort = FALSE)` would be important. A final difference in the defaults regards missing value removal. In *collapse*, the default is `na.rm = TRUE`, which also has a small performance cost. So ideally you would use `fmean(na.rm = FALSE)` in benchmarks without missing values. 

So in general: for benchmarking different libraries it is also important to look at the default settings of libraries to make sure you are comparing apples with apples under the hood: are the defaults set up for greater convenience or maximum performance? What is the default behavior regarding sorting, missing values, number of threads etc...

**Comment by shokru** [comment]
Dear Sebastian, you are very right. I made the changes and indeed {collapse} is much more competitive.
I did not change the sorting options, as I prefer to keep sorting on, but did not find how to activate it in {arrow}...
I have a question: is there an equivalent of the "across(...)" syntax in {collapse}? 
So that I can test the lengthier last exercise with {collapse} as well. 
Thank you for your guidance.

**Comment by SebKrantz** [comment]
Thanks, so it seems that arrow does not do sorted grouping out of the box at the moment. For perfect equivalence you would probably need to follow up with an arrange(). But In understand your goals may be more simple just testing "out of the box performance", in which case you could just state that arrow is not strictly doing the same thing. 

Regarding the updated benchmark, it would also be more efficient to write 

```
data %>% fgroup_by(DATE) %>% fsummarise(m = fmean(is.finite(mom1m)))
```
instead of 
```
data %>% fgroup_by(DATE) %>% fselect(mom1m) %>% fmutate(mom1m = is.finite(mom1m)) %>% fmean()
```
as the latter evaluates `is.finite()` split by groups before aggregating, which is not necessary. Regarding `across()`, yes collapse supports it, see [documentation](https://sebkrantz.github.io/collapse/reference/across.html), however it does not work with tidyselect, you can just pass jour column names or indices directly to across(), see examples. In your benchmark I see you want to apply a function across all columns (everything() in tidyselect parlance). I *collapse* you can use a shortcut with the BY() function e.g. 

```r
data_table %>% fgroup_by(DATE) %>% BY(prop_fin)
``` 
Is equivalent to 
```r
data_table %>% fgroup_by(DATE) %>%  fsummarise(across(NULL, prop_fin))
```
Another option, probably the fastest here, would be 

```r
data_table %>% ftransformv(-DATE, is.finite) %>% fgroup_by(DATE) %>% fmean()
```
This is faster because `fmean()` is vectorized across groups when called like this or inside `fsummarise()` or `fmutate()`, and thus much faster than `mean()`.

**Comment by shokru** [comment]
Thanks again. I have updated the benchmark. And indeed {collapse} performs very well.
I wonder if you have compared its speed with similar tasks in other languages (Python, Julia) and optimized libraries as well.
My guess is that {collapse} is hard to beat!

**Comment by SebKrantz** [comment]
I'd say {collapse} is hard to beat on these medium sized datasets of a few million obs in settings where we have many groups or are doing more complex statistical operations. For very large datasets (100 million obs +), simple statistical operations (sum, mean), and a moderate number of groups compared to the data size (e.g. 10k-100k groups), frameworks like duckdb, arrow, polars etc. are better optimized because they utilize the computer hardware better (using SIMD instructions and optimized data formats) than any library written using R's C API could. That being said, {collapse} integrates much better with R, supporting vectors, matrices, and the most common data frame like classes out of the box.
